//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Two {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Two.IBookServiceTwo")]
    public interface IBookServiceTwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServiceTwo/GetAll", ReplyAction="http://tempuri.org/IBookServiceTwo/GetAllResponse")]
        Data.Book[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServiceTwo/GetAll", ReplyAction="http://tempuri.org/IBookServiceTwo/GetAllResponse")]
        System.Threading.Tasks.Task<Data.Book[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceTwoChannel : Client.Two.IBookServiceTwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceTwoClient : System.ServiceModel.ClientBase<Client.Two.IBookServiceTwo>, Client.Two.IBookServiceTwo {
        
        public BookServiceTwoClient() {
        }
        
        public BookServiceTwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceTwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceTwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceTwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.Book[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Data.Book[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
